name: Run version update
on:
  # Allows you to run this workflow manually from the Actions tab or rest API
  workflow_dispatch:
    branches:
      - 'main'
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get current sprint number
        id: get-sprint-number
        run: |
          SPRINT_NUMBER=$(curl -s -X GET -H "Content-Type: application/json" https://639f96897aaf11ceb89d5729.mockapi.io/jira/getBoard/2555 | jq -r '.values[0].name+ ".0" | match("[^a-z A-Z]+")| .string')
          echo ${SPRINT_NUMBER} >> $GITHUB_OUTPUT
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: Set Git config
        run: |
          git config --global user.name "'Automated Version Bump'"
          git config --global user.email "my-email@example.com"
      - name: 'Update package.json'
        run:  echo "`jq '.version="${{steps.get-sprint-number.outputs.SPRINT_NUMBER}}"' package.json`" > package.json
      - name: Commit the changes
        run: |
          git add package.json
          git commit -m "Update package.json version to ${{steps.get-sprint-number.outputs.SPRINT_NUMBER}}"
      - name: Create Tag and Push
        run: |
          git tag -a v${{steps.get-sprint-number.outputs.SPRINT_NUMBER}} -m "release tag version- v${{steps.get-sprint-number.outputs.SPRINT_NUMBER}}"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
