name: Run version update
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
      - 'main'
    inputs:
      version:
        description: 'Version to create, eg, 5.11.2'
        required: true
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: Set Git config
        run: |
          git config --global user.name "'Automated Version Bump'"
          git config --global user.email "my-email@example.com"
      - name: 'Update package.json'
        run:  echo "`jq '.version="${{ github.event.inputs.version }}"' package.json`" > package.json
      - name: Commit the changes
        run: |
          git add package.json
          git commit -m "Update package.json version to ${{ github.event.inputs.version }}"
      - name: Create Tag and Push
        run: |
          git tag -a v${{ github.event.inputs.version }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
