name: Call the Jira workflow
on:
  workflow_dispatch:
    branches:
      - 'main'
jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  call-workflow:
    uses: sasidharankp/hooks/.github/workflows/jira.yml@main
    
 
