name: Call the Jira workflow
on:
  workflow_call:
    branches:
      - 'main'
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jira workflow
        uses: sasidharankp/hooks/.github/workflows/jira.yml@v24.4.0
        run: echo "Workflow Triggered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
