name: Call the Jira workflow
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  call-workflow:
    uses: sasidharankp/hooks/.github/workflows/jira.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}